### ISSUE TITLE
Fill out Message struct and implement ser and de for all of it

### ISSUE THREAD

**Issue by futurepaul** [futurepaul/nostr-rs#5]
I believe we want something like
```
#[derive(Debug, PartialEq)]
 pub enum Message {
     Notice { message: String },
     Event { subscription_id: String, event: Event },
     Req { subscription_id: String, filter: SubscriptionFilter },
     Close { subscription_id: String }
 }
 ```

There are actually differences between what an `Event` looks like between if you're a client -> relay, vs relay -> client:

## From client to relay
```
["EVENT", <event JSON as defined above>], used to publish events.
["REQ", <id>, <filter JSON>...], used to request events and subscribe to new updates.
["CLOSE", <id>]
```

## From relay to client
```
["EVENT", <subscription id>, <event JSON as defined above>]
["NOTICE", <message>]
```

So either we have an `ClientMessage` and a `RelayMessage` or we just handle the special cases all on `Message`

**Comment by emeceve** [comment]
Make two distinct structures will help when `match` the result from incoming message handler, since clients will only handle `RelayMessage` as well relay will only handle `ClientMessage`

**Comment by emeceve** [comment]
I think this issue can be closed
